config/routes.rb
FinalSpeschke::Application.routes.draw do
  resources :subscribers

end

app/models/subscribers.rb
class Subscribers < ActiveRecord::Base
  attr_accessible :ID_Number, :Name, :Phone
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  respond_to :xml

  def index
    @subscribers = Subscribers.all
    render :xml => @subscribers

    #respond_to do |format|
    #  format.html # index.html.erb
    #  format.json { render json: @subscribers }
    #
    # end
  end

  def show
    @subscribers = Subscribers.find(params[:id])
    render :xml => @subscribers

    #respond_to do |format|
    #  format.html # show.html.erb
    #  format.json { render json: @subscribers }
    #end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinalSpeschke</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/subscribers/index.html.erb
<h2>Subscribers</h2>

<table>
     <tr>
        <th>
            <h3>Subscriber Information</h3>
        </th>
     </tr>
</table>
<table>
    <tr>
    <th align = "left" width = "150x;">Name</th>
    <th align = "left" width = "150px;">Phone</th>
    <th align = "left" width = "50px;">ID</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @subscribers.each do |subscribers| %>
      <tr>
        <td><%= subscribers.Name %></td>
        <td><%= subscribers.Phone %></td>
        <td><%= subscribers.ID_Number %></td>
        <td><%= link_to 'Show', subscribers %></td>
      </tr>
  <% end %>
</table>

app/views/subscribers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h3>Subscriber Information</h3>
</p>

<p>
  <b>Name:</b>
  <%= @subscribers.Name %>
</p>

<p>
  <b>Phone:</b>
  <%= @subscribers.Phone %>
</p>

<p>
  <b>ID:</b>
  <%= @subscribers.ID_Number %>
</p>



<%= link_to 'Back', subscribers_path %>
 